<?php
return [
    'gender' => ['male', 'female', 'other'],
    'religion' => ['islam', 'christianity', 'hinduism', 'other'],
    'nationality' => [
        'pakistan',
        'india',
        'bangladesh',
        'afghanistan',
        'china',
        'saudi arabia',
        'united arab emirates',
        'united states',
        'united kingdom',
        'canada',
        'australia',
        'turkey',
        'iran',
        'indonesia',
        'malaysia',
        'egypt',
        'south africa',
        'germany',
        'france',
        'italy',
        'other',
    ],
    'class_shift' => ['morning', 'evening', 'other'],
    'inclusive' => ['no disability', 'physical', 'visual', 'hearing', 'intellectual', 'other'],
    'father_profession' => ['unemployed', 'private/self employed', 'government', 'other'],
    'mother_profession' => ['house wife', 'private/self employed', 'government', 'other'],
    'education' => ['none', 'primary', 'middle', 'matric', 'intermediate', 'graduate', 'post graduate'],
    'income_levels' => [
        'income level between rs. 0 - 20,000',
        'income level between rs. 20,001 - 27,000',
        'income level between rs. 27,001 - 35,000',
        'income level between rs. 35,001 - 50,000',
        'income level above rs. 50,000',
    ],
    'mother_incomes' => [
        'none',
        'income level between rs. 0 - 20,000',
        'income level between rs. 20,001 - 27,000',
        'income level between rs. 27,001 - 35,000',
        'income level between rs. 35,001 - 50,000',
        'income level above rs. 50,000',
    ],
];
